service: echo-api

# Note: I write these examples using the latest version of Serverless. I pin the example
# to that version so that I know it will work for you even if you find it a year later.
# Likely, you can remove this line and use the example with any recent version of
# Serverless. Give it a shot if you're using a different version.
frameworkVersion: "=1.34.1"

custom:
   defaultRegion: us-east-1
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}
   objectPrefix: '${self:service}-${self:custom.stage}'

provider:
   name: aws
   runtime: nodejs8.10

functions:
   echo:
      handler: src/handler.echo
      events:
         - http: 'ANY /'
         - http: 'ANY {proxy+}'
